-- Drop all tables
DROP TABLE IF EXISTS tentativa;
DROP TABLE IF EXISTS plano_exercicio;
DROP TABLE IF EXISTS plano;
DROP TABLE IF EXISTS exercicio;
DROP TABLE IF EXISTS grupo;
DROP TABLE IF EXISTS paciente;
DROP TABLE IF EXISTS profissional;
DROP TABLE IF EXISTS cidade;
DROP TABLE IF EXISTS uf;